// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VidrieriaPresupuestos.Web.Data;

#nullable disable

namespace VidrieriaPresupuestos.Web.Migrations
{
    [DbContext(typeof(VidrieriaContext))]
    [Migration("20260728232112_ModeloCompletoPresupuestos")]
    partial class ModeloCompletoPresupuestos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.CargoAdicional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoCalculado")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoValor")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId");

                    b.ToTable("CargosAdicionales");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.ItemPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Origen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeComision")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seccion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId");

                    b.ToTable("ItemsPresupuesto");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionTrabajo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorNeto")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.CargoAdicional", b =>
                {
                    b.HasOne("VidrieriaPresupuestos.Domain.Entidades.Presupuesto", "Presupuesto")
                        .WithMany("CargosAdicionales")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.ItemPresupuesto", b =>
                {
                    b.HasOne("VidrieriaPresupuestos.Domain.Entidades.Presupuesto", "Presupuesto")
                        .WithMany("Items")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presupuesto");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.Presupuesto", b =>
                {
                    b.HasOne("VidrieriaPresupuestos.Domain.Entidades.Cliente", "Cliente")
                        .WithMany("Presupuestos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.Cliente", b =>
                {
                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("VidrieriaPresupuestos.Domain.Entidades.Presupuesto", b =>
                {
                    b.Navigation("CargosAdicionales");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
